import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import 'remixicon/fonts/remixicon.css'
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";


const fontPoppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]

})

export const metadata = {
  title: "PT. JAYA RIZKY ALEXANDRA",
  description: "Generated by Nerz789",
  icons: {
    icon: "/logo.png",
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
<body
  id="beranda"
  className={`${fontPoppins.className} antialiased bg-[#0B1020] text-slate-200`}
>



  
        <ScrollToTop/>
        <Navbar />
        <div className="container mx-auto px-4">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
